image: alpine/3.23
packages:
  - docker
tasks:
  - init-docker: |
      sudo service docker start
      sudo addgroup ${USER} docker
  - install-golang: |
      cd /tmp
      curl -O -sSfL https://go.dev/dl/go1.26.0.linux-amd64.tar.gz
      [ "$(sha256sum go1.26.0.linux-amd64.tar.gz | cut -d ' ' -f 1)" == "aac1b08a0fb0c4e0a7c1555beb7b59180b05dfc5a3d62e40e9de90cd42f88235" ]
      sudo tar -C /usr/local -xzf go1.26.0.linux-amd64.tar.gz
      sudo ln -s /usr/local/go/bin/go /usr/local/bin/go
      sudo ln -s /usr/local/go/bin/gofmt /usr/local/bin/gofmt
  - install-golangci-lint: |
      cd /tmp
      curl -O -sSfL https://github.com/golangci/golangci-lint/releases/download/v2.10.1/golangci-lint-2.10.1-linux-amd64.tar.gz
      [ "$(sha256sum golangci-lint-2.10.1-linux-amd64.tar.gz | cut -d ' ' -f 1)" == "dfa775874cf0561b404a02a8f4481fc69b28091da95aa697259820d429b09c99" ]
      sudo tar -xzf golangci-lint-2.10.1-linux-amd64.tar.gz -C /usr/local/bin --strip-components 1 golangci-lint-2.10.1-linux-amd64/golangci-lint
  - install-romero: |
      go install git.sr.ht/~ne02ptzero/romero@latest
      [ -x "$(go env GOPATH)" ]
      sudo ln -s "$(go env GOPATH)"/bin/romero /usr/local/bin/romero
  - go-modules: |
      cd wtf-go
      go mod tidy -diff
  - go-test: |
      cd wtf-go
      go test -v ./...
  - linting: |
      cd wtf-go
      golangci-lint run ./...
  - docker-build: |
      cd wtf-go
      docker build --file ./build/Dockerfile .
  - doc-build: |
      cd wtf-go/docs
      romero build
